# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - "vars/{{ overwrite_distribution | default(ansible_distribution) }}.yml"
    - "vars/{{ overwrite_distribution | default(ansible_distribution) }}-{{ overwrite_machine | default(ansible_machine) }}.yml"
    - "vars/custom_patchmgmt.yml"

  vars:
    root_zfs_pool: "{{ ansible_proc_cmdline.rpool }}"
    distro_filesystem_path: "{{ root_zfs_pool }}/ROOT/{{ ansible_distribution }}"
    distro_snapshot_path: "{{ root_zfs_pool }}/ROOT/{{ ansible_distribution }}@before_upgrade"
    distro_old_boot_path: "{{ distro_filesystem_path }}_old_boot"
    grub_filesystem_path: "{{ root_zfs_pool }}/data/grub"

### TODO: this feature is not implemented yet
#    snapshots:
#      - "{{ grub_filesystem_path }}"

  tags:
    - pre_patch

  roles:
    - name: Verify The System
      role: verify_system
      tags:
        - verify_system

    - name: Don't Run As The Root User
      role: stop_if_root
      tags:
        - stop_if_root

    - name: Unmount The List of Binds (in case they was mounted - can easily happen in testing)
      role: umount_binds
      tags:
        - mount_binds

    - name: Snapshot & Clone The ROOT (/) Filesystem
      role: snapshot_and_clone
      tags:
        - zfs_checks

    - name: Mount The List of Binds
      role: mount_binds
      tags:
        - mount_binds


- hosts: chroot
  connection: sudo_chroot
  gather_facts: true

  tags:
    - patch

  vars_files:
    - "vars/{{ overwrite_distribution | default(ansible_distribution) }}.yml"
    - "vars/{{ overwrite_distribution | default(ansible_distribution) }}-{{ overwrite_machine | default(ansible_machine) }}.yml"
    - "vars/custom_patchmgmt.yml"

  vars: 
    root_zfs_pool: "{{ ansible_proc_cmdline.rpool }}"
    ansible_chroot_exe: arch-chroot
    distro_filesystem_path_without_zpool: "/ROOT/{{ ansible_distribution }}_next_boot"

  roles:
    - name: Upgrade All Packages
      role: patch
      tags:
        - patch_upgrade

    - name: Generate new grub.cfg
      role: grub_mkconfig
      tags:
        - patch_grub


- hosts: localhost
  gather_facts: true

  vars_files:
    - "vars/{{ overwrite_distribution | default(ansible_distribution) }}.yml"
    - "vars/{{ overwrite_distribution | default(ansible_distribution) }}-{{ overwrite_machine | default(ansible_machine) }}.yml"
    - "vars/custom_patchmgmt.yml"

  vars:
    root_zfs_pool: "{{ ansible_proc_cmdline.rpool }}"
    distro_filesystem_path: "{{ root_zfs_pool }}/ROOT/{{ ansible_distribution }}"
    distro_snapshot_path: "{{ root_zfs_pool }}/ROOT/{{ ansible_distribution }}@before_upgrade"

  tags:
    - post_patch

  roles:
    - name: Don't Run As The Root User
      role: stop_if_root
      tags:
        - stop_if_root

    - name: Unmount The (ZFS) next_boot
      role: unmount_next_boot
      tags:
        - unmount_next_boot

  post_tasks:
    - block:
        - name: Delete clone and snapshot, because patch failed
          zfs:
            name: "{{ item }}"
            state: absent
          loop:
            - "{{ distro_next_boot_path }}"
            - "{{ distro_snapshot_path }}"

        - name: "Patch Management Failed :("
          fail:
            msg: "Patch Management failed, hopefully to goes better next time. Clean have been performed"
      when: not hostvars['/tmp/pre-pare_next_boot'].patch_succeeded
      tags:
        - delete_snapshot_because_of_failure

    - name: Set bootfs (zpool prop) to the next_boot
      ansible.builtin.command: 
        cmd: "sudo zpool set bootfs='{{ distro_next_boot_path }}' '{{ root_zfs_pool }}'"
        warn: no
      tags:
        - update_bootfs

