# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- block:
    - name: Run pacman
      pacman:
        upgrade: yes
        update_cache: yes
      register: _result_pacman

    - name: Run pacman (debug)
      debug:
        var: _result_pacman

    - name: Upgrade packages from the aur
      become: yes
      become_user: "{{ patch_user }}"
      command: trizen -Sy --aur --noconfirm
      register: _result_trizen
      failed_when:
        - _result_trizen | json_query(filter) | count > 0 or _result_trizen.rc != 0
      vars:
        filter: "stdout_lines[?contains(@, 'Error! Bad return status for module build on kernel')]"

    # TODO: remove this when the filter has been confirmed to work
    - name: Install ZFS packages - Trizen (debug)
      debug:
        var:
          - _result_trizen | json_query(filter) | count > 0
          - _result_trizen.rc != 0
      vars:
        filter: "stdout_lines[?contains(@, 'Error! Bad return status for module build on kernel')]"

    - name: Upgrade packages from the aur (debug)
      debug:
        var: _result_trizen

    - name: Set the variable indicating that the patch succeeded
      set_fact:
        patch_succeeded: true
  rescue:
    - name: Set the variable indicating that the patch failed
      set_fact:
        patch_succeeded: false

