- name: Copy file with owner and permissions
  copy:
    content: |
      build() {
        add_binary {{ initcpio_hook_dir }}/generator_patchmgmt /usr/lib/systemd/system-generators/
      }
    dest: "{{ initcpio_install_dir }}/sd-patchmgmt"
    owner: root
    group: root
    mode: '0644'


- name: Ensure the directory '{{ initcpio_hook_dir }}' exists
  file:
    path: "{{ initcpio_hook_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755


- name: Copy file with owner and permissions
  copy:
    content: |
      #!/usr/bin/env sh
      set -eu

      LOG_FILE="/run/log/generator_patchmgmt.log"

      exec 3>&1 4>&2
      trap 'exec 2>&4 1>&3' 0 1 2 3
      exec 1>${LOG_FILE} 2>&1

      for argv in $@; do
        echo $argv
      done

    dest: "{{ initcpio_hook_dir }}/generator_patchmgmt"
    owner: root
    group: root
    mode: '0755'
