- name: Create the mkinitcpio module for patchmgmt
  copy:
    src: mkinitcpio-sd-patchmgmt/sd-patchmgmt.j2
    dest: "{{ initcpio_install_dir }}/sd-patchmgmt"
    owner: root
    group: root
    mode: 0644

- name: Ensure the directory '{{ initcpio_hook_dir }}' exists
  file:
    path: "{{ initcpio_hook_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Create the init generator for patchmgmt (update: remove file)"
  file:
    path: "{{ initcpio_hook_dir }}/generator_patchmgmt"
    state: absent

- name: Create the script to handle *_next_boot filesystems
  template:
    src: "mkinitcpio-sd-patchmgmt/patchmgmt-next-boot.sh.j2"
    dest: "{{ initcpio_hook_dir }}/patchmgmt-next-boot.sh"
    owner: root
    group: root
    mode: 0755

- name: Create the systemd service which run the patchmgmt-next-boot.sh script
  template:
    src: "mkinitcpio-sd-patchmgmt/patchmgmt-next-boot.service.j2"
    dest: "{{ initcpio_hook_dir }}/patchmgmt-next-boot.service"
    owner: root
    group: root
    mode: 0755
