---
- name: Copy pre-build package of trizen
  copy:
    src: trizen-1:1.62-1-any.pkg.tar.xz
    dest: /tmp/trizen.pkg.tar.xz

- name: Install form the aur
  command: pacman -U --noconfirm --noprogressbar --needed /tmp/trizen.pkg.tar.xz
  register: result

- debug:
    var: result
  when: debug | default(false)