# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Check that the time zone exists
  stat:
    path: "/usr/share/zoneinfo/{{ time_zone }}"
  register: _result
  
- fail:
    msg: "The time zone: {{ time_zone }} doesn't exist"
  when: not _result.stat.exists or not _result.stat.isreg
    
- name: Set the time zone
  file:
    state: link
    src: "/usr/share/zoneinfo/{{ time_zone }}"
    path: "/etc/localtime"

- name: Verify that the list of locale exist
  include_tasks: verify_locale.yml
  loop: "{{ locale }}"

- name: Setup locale config
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf

- name: Generate locale
  ansible.builtin.command:
    cmd: locale-gen

- name: Set hostname
  copy:
    content: "{{ hostname }}\n"
    dest: "/etc/hostname"
    owner: root
    group: root
    mode: 0544

- name: Set network to default dhcp with systemd
  template:
    src: "systemd-dhcp.network.j2"
    dest: "/etc/systemd/network/systemd-dhcp.network"
    owner: root
    group: root
    mode: 0644
  when:
    - systemd is defined
    - systemd.network is defined

- name: Allow members of the 'wheel' group to use sudo
  copy:
    content: "%wheel ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/enable_sudo_access_4_members_of_wheel"
    owner: root
    group: root
    mode: 0440

- name: Setup admin & root user
  include_tasks: manage_users.yml
