# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: "Create hash of the password for the user '{{ admin_user }}'"
  ansible.builtin.command:
    cmd: >-
      python3 -c "import crypt; print(crypt.crypt('{{ admin_pass }}'))"
  when: admin_pass_hash is not defined
  register: admin_pass_hash

- name: "Create hash of the password for the user '{{ admin_user }} (set_fact)'"
  set_fact:
    admin_pass_hash: "{{ admin_pass_hash.stdout }}"
  when: admin_pass_hash.stdout is defined

- name: Create hash of the password for the user root
  ansible.builtin.command:
    cmd: >-
      python3 -c "import crypt; print(crypt.crypt('{{ root_pass }}'))"
  when: 
    - root_pass_hash is not defined
    - root_pass is defined
  register: _root_pass_hash

- name: Create hash of the password for the user root (set_fact)
  set_fact:
    root_pass_hash: "{{ root_pass_hash | default(_root_pass_hash.stdout) | default(admin_pass_hash) }}"

- name: Set password for root
  user:
    name: root
    shell: "{{ shell_to_use }}"
    password: "{{ root_pass_hash }}"

- name: Add the group for the admin user
  group:
    name: "{{ admin_user }}"
    system: no

- name: Add the admin user
  user:
    name: "{{ admin_user }}"
    group: "{{ admin_user }}"
    groups: wheel
    password: "{{ admin_pass_hash }}"
    state: present
    home: "/home/{{ admin_user }}"
    shell: "{{ shell_to_use }}"
    system: no
    update_password: on_create

- name: Set the correct permissions for the home folder of the admin user
  file:
    path: "/home/{{ admin_user }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0700
