# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Unmount the list of binds 
  command: "sudo umount '{{ next_boot_mountpoint }}{{ item }}'"
  args:
    warn: no
  with_items: "{{ binds }}"
  register: _result
  failed_when: not (_result.rc != 0 or _result.rc != 32)
  tags:
    - mount_binds

