# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: "Gets stat of the folder '{{ next_boot_mountpoint }}'"
  stat:
    path: "{{ next_boot_mountpoint }}"
  register: _result

- name: "Gets stat of the folder '{{ next_boot_mountpoint }}'"
  debug:
    var: _result
  when:
    - not _result.stat.exists

- name: Unmount the entire next_boot envirement
  ansible.builtin.command:
    cmd: "sudo umount --recursive '{{ next_boot_mountpoint }}'"
    warn: no
  when:
    - _result.stat.exists
    - _result.stat.isdir

#- name: Gather ZFS fact about the distro partition
#  zfs_facts:
#    name: "{{ distro_next_boot_path }}"
#    recurse: no
#    type: all
#    properties: all

#- debug:
#    var: ansible_zfs_datasets

#- name: Unmount the (zfs) next_boot partition
#  ansible.builtin.command:
#    cmd: "zfs unmount {{ distro_next_boot_path }}"
#  when: ansible_zfs_datasets | json_query(json_filter) | count == 1
#  vars:
#    json_filter: "[?name=='{{ distro_next_boot_path }}' && mounted=='yes']"

- name: Config the zfs settings for the next_boot
  zfs:
    name: "{{ distro_next_boot_path }}"
    state: present
    extra_zfs_properties:
      canmount: noauto
      mountpoint: "/"

