# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Reads the entire grub.cfg.j2 file
  local_action:
    module: command
    cmd: "cat '{{ playbook_dir }}/roles/{{ role_name }}/templates/grub.cfg.j2'"
  register: _grub_cfg

- name: Check if /boot/grub/grub.cfg exists
  stat:
    path: /boot/grub/grub.cfg
  register: _result

- name: Read the grub.cfg file for backup
  ansible.builtin.command:
    cmd: "sudo cat /boot/grub/grub.cfg"
  register: _old_grub_cfg
  when:
    - _result.stat.exists
    - _result.stat.isreg

- name: Generates a new grub.cfg file based on a template
  shell: |
    echo {{ playbook_dir }}
    cat <<'zzzEOFzzz' | python3 | sudo /usr/bin/tee "/boot/grub/grub.cfg"
    import sys
    from jinja2 import Template, Environment, StrictUndefined
    from jinja2.exceptions import UndefinedError

    template = Template("""{{_grub_cfg.stdout}}""")
    template.environment.undefined = StrictUndefined

    try:
      grub_config = template.render(
        distro_filesystem_path_without_zpool = "{{ distro_filesystem_path_without_zpool }}",
        kernel_path_dir = "{{ kernel_path_dir }}",
        kernel_filename = "{{ kernel_filename }}",
        initrd_filename = "{{ initrd_filename }}",
        initrd_fallback_filename = "{{ initrd_fallback_filename }}",
        root_zfs_pool = "{{ root_zfs_pool }}",
        kernel_boot_cmd_extra = "{{ kernel_boot_cmd_extra }}",
        consoles = list(map(lambda sc: 'console={}'.format(sc), {{ serial_console }})) if {{ serial_console if serial_console else 'None' }} else [],
      )
      print(grub_config)
    except UndefinedError as e:
      stdout = """{{ _old_grub_cfg.stdout | default('') }}"""
      if stdout:
        print(stdout)
      else:
        print('ERROR: There was no /boot/grub/grub.cfg to backup\n\n', file=sys.stderr)
      print(e, file=sys.stderr)
    zzzEOFzzz
  args:
    warn: no
  register: _result

- name: Generates a new grub.cfg file based on a template (Failed)
  fail:
    msg: "{{ 'Error:\n{}'.format(_result.stderr_lines | join('\n')) }}"
  when: _result.stderr_lines | count > 0
