# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Generates a new grub.cfg file based on a template
  shell: |
    cat <<'zzzEOFzzz' | python3 | sudo /usr/bin/tee "/boot/grub/grub.cfg"
    from jinja2 import Template,Environment
    from jinja2.loaders import FileSystemLoader

    with open("roles/grub_mkconfig/templates/grub.cfg.j2", 'r') as content_file:
      grub_config = Template(
        content_file.read()
      ).render(
        distro_filesystem_path_without_zpool = "{{ distro_filesystem_path_without_zpool }}",
        kernel_path_dir = "{{ kernel_path_dir }}"
      )

      print(grub_config)
    zzzEOFzzz

