# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
### Install Trizen packages manager
- name: Copy pre-build package of trizen
  copy:
    src: trizen-1:1.63-1-any.pkg.tar.xz
    dest: /tmp/trizen.pkg.tar.xz

- name: Install form the aur
  command: pacman -U --noconfirm --noprogressbar --needed /tmp/trizen.pkg.tar.xz
  register: result

- debug:
    var: result
  when: debug | default(false)

### Added 3rd-party Repo
- name: Add the repository archzfs
  blockinfile:
    path: /etc/pacman.conf
    insertbefore: "{{ item.insertbefore }}"
    block: "{{ item.block }}"
  with_items: "{{ add_extra_repos }}"
  when: add_extra_repos is defined

### Install the Linux kernel
- name: Install kernel packages
  pacman:
    name:
      - "{{ kernel_package }}"
      - "{{ kernel_package }}-headers"
    state: latest
    update_cache: yes
    update_cache_extra_args: --needed
  register: _result

- name: Install packages (debug)
  debug:
    var: _result

### Install ZFS packages
- block:
    - name: Install ZFS packages - Pacman
      pacman:
        name: "{{ zfs_packages }}"
      register: _result

    - name: using Pacman (debug)
      debug:
        var: _result
  rescue:
    - name: Install ZFS packages - Trizen and the AUR
      become: yes
      become_user: "{{ patch_user }}"
      command: >-
        trizen -S --noconfirm --needed --noprogressbar
        {{ zfs_packages | join(' ') }}
      register: _result

    - name: Install ZFS packages (debug)
      debug:
        var: _result

