# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Install & Config the OS and architecture specific stuff
  include_tasks: "os_{{ os }}-{{ architecture }}.yml"

- name: Install & Config the OS specific stuff
  include_tasks: "os_{{ os }}.yml"
