# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Config the base OS and architecture stuff
  include_tasks: "os_{{ os }}-{{ architecture }}.yml"

- name: Config the base OS stuff
  include_tasks: "os_{{ os }}.yml"
