# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Install packages
  apt:
    name:
      - grub2-common
  register: _result

- name: Install packages (debug)
  debug:
    var: _result
