# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Find the the block device of the zpool
  command: "zpool status -PL {{ root_zfs_pool }}"
  register: _result

- name: Find the the block device of the zpool (set_fact)
  set_fact:
    zpool_block_device_partition: '{{ _result.stdout | regex_search("/dev/[^ ]+")}}'

- name: Find the the block device of the EFI (set_fact)
  set_fact:
    efi_block_device_partition: '{{ zpool_block_device_partition | regex_replace("2$", "1")}}'

- name: Find the the UUID of the EFI block device (set_fact)
  set_fact:
    efi_block_device_partition_uuid: '{{ ansible_devices | json_query(filter) | first }}'
  vars:
    filter: '*.partitions[][{{ efi_block_device_partition | basename }}][]["uuid"][]'

- name: Mount the EFI partition by UUID (debug)
  debug:
    var: efi_block_device_partition_uuid
  when: debug | default(false)

- name: Mount the EFI partition by UUID
  mount:
    path: "{{ mountpoint_efi_partition }}"
    src: "UUID={{ efi_block_device_partition_uuid }}"
    fstype: vfat
    state: mounted

- name: Install the Grub package
  pacman:
    name:
      - grub
      - efibootmgr
    state: latest
    update_cache: yes
    update_cache_extra_args: --needed

- name: Install Grub as the boot loader
  shell: |
    export ZPOOL_VDEV_NAME_PATH=1
    grub-install --target={{ grub_install_target }} --efi-directory={{ mountpoint_efi_partition }} --removable
