# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Find the the block device of the zpool
  command: "zpool status -PL {{ root_zfs_pool }}"
  register: _result

- name: Find the the block device of the zpool (set_fact)
  set_fact:
    zpool_block_device_partition: "{{ _result.stdout | regex_search('/dev/[^ ]+') }}"

- name: Mount the EFI partition by UUID (debug)
  debug:
    var: ansible_devices | json_query(filter)
  when: debug | default(false)
  vars:
    filter: '*.partitions[]["nvme0n1p1"][]["uuid"][]'

- name: Mount the EFI partition by UUID
  mount:
    path: "{{ mountpoint_efi_partition }}"
    src: "UUID={{ ansible_devices | json_query(filter) | first }}"
    fstype: vfat
    state: mounted
  vars:
    filter: '*.partitions[]["nvme0n1p1"][]["uuid"][]'

- name: Install the Grub package
  pacman:
    name:
      - grub
      - efibootmgr
    state: latest
    update_cache: yes
    update_cache_extra_args: --needed

- name: Install Grub as the boot loader
  shell: |
    export ZPOOL_VDEV_NAME_PATH=1
    grub-install --target={{ grub_install_target }} --efi-directory={{ mountpoint_efi_partition }} --removable
