# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Make sure the necessary packages are installed
  pacman:
    name: 
      - arch-install-scripts
      - python-jmespath
      - python-jinja
    state: present
    update_cache_extra_args: --needed

