# ex: set tabstop=8 softtabstop=0 expandtab shiftwidth=2 smarttab:
---
- name: Add the repository archzfs
  blockinfile:
    path: /etc/pacman.conf
    insertbefore: "{{ item.insertbefore }}"
    line: "{{ item.block }}"
  with_items: "{{ add_extra_repos }}"
  when: add_extra_repos is defined

- name: Install kernel packages
  pacman:
    name:
      - "{{ kernel_package }}"
      - "{{ kernel_package }}-headers"
    state: latest
    update_cache: yes
    update_cache_extra_args: --needed
  register: _result

- name: Install packages (debug)
  debug:
    var: _result

- name: Install ZFS packages
  become: yes
  become_user: "{{ patch_user }}"
  command: >- 
    trizen -S --noconfirm --needed --noprogressbar
    {{ zfs_packages | join(' ') }}
  register: _result

- name: Install ZFS packages (debug)
  debug:
    var: _result

- name: Gather facts about ZFS
  zfs_facts:
    name:
    recurse: yes
    
- debug:
    var: ansible_zfs_datasets
  when: debug | default(false)

### TODO: Evaluate if this is still needed
- name: Initiate variable 'root_zfs_pool'
  set_fact:
    root_zfs_pool: "{{ ansible_zfs_datasets | json_query(filter) | first | regex_replace('/.+', '') }}"
  vars:
    filter: "[?mountpoint=='{{ next_boot_mountpoint }}'].name"

### TODO: Evaluate if this is still needed
- debug:
    var: root_zfs_pool
  when: debug | default(false)

- name: Find the the block device of the zpool
  command: "zpool status -PL {{ root_zfs_pool }}"
  register: _result

- name: Find the the block device of the zpool (set_fact)
  set_fact:
    zpool_device_block: "{{ _result.stdout | regex_search('/dev/[^ ]+') | regex_replace('^/dev/(.+)[0-9]+$', '\\1') }}"

- debug:
    var: ansible_devices[zpool_device_block]
  when: debug | default(false)

- name: Mount the EFI partition by UUID
  mount:
    path: "{{ mountpoint_efi_partition }}"
    src: "UUID={{ ansible_devices[zpool_device_block].partitions[partiton_1].uuid }}"
    fstype: vfat
    state: mounted
  vars:
    partiton_1: "{{ zpool_device_block }}1"

- name: Install the Grub package
  pacman:
    name:
      - grub
      - efibootmgr
    state: latest
    update_cache: yes
    update_cache_extra_args: --needed

- name: Install Grub as the boot loader
  shell: |
    export ZPOOL_VDEV_NAME_PATH=1
    grub-install --target={{ grub_install_target }} --efi-directory={{ mountpoint_efi_partition }} --removable
